DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR2(255),
    COUNTRY VARCHAR2(255),
    DEPARTEMENT INTEGER,
    REGION VARCHAR2(255),
    ALTITUDE INTEGER,
    LATITUDE INTEGER,
    LONGITUDE INTEGER,
    ZIPCODE INTEGER
);

INSERT INTO CITY (ID, NAME, COUNTRY, DEPARTEMENT, REGION, ALTITUDE, LATITUDE, LONGITUDE, ZIPCODE)
    VALUES (1, 'Brest', 'France', 29, 'Bretagne', 100, 200, 300, 29200);